### ISSUE TITLE
这个样式怎么都没了

### ISSUE THREAD

**Issue by xinshengBoy** [Nikati/WebStack-XML-Guns#1]
![QQ截图20200512122656](https://user-images.githubusercontent.com/16789055/81638505-fe696700-944b-11ea-856e-eab681c3a765.png)
这样的该怎么解决呢（PS:小白选手，望不要嫌弃）

**Comment by Nikati** [comment]
按f12 查看那些样式没加载出来

**Comment by xinshengBoy** [comment]
![QQ截图20200512140355](https://user-images.githubusercontent.com/16789055/81644085-a76a8e80-9459-11ea-80d8-90e9c720775f.png)
![QQ截图20200512140501](https://user-images.githubusercontent.com/16789055/81644091-a9cce880-9459-11ea-91a4-0e6e961cc0fb.png)
有很多个js和cs都加载不出来，但webapp里面都有的吧，是不是因为那个tmp的问题呢
